console.log("Hello World");
let studentName = "John Doe";
console.log(studentName);
let age = 20;
console.log(age);
let name = "Jane Smith";
let age2 = 25;
console.log(name,age2);
let country = "India";
console.log(country);
let employeeName = "Alice Johnson";
console.log(employeeName);
console.log(typeof employeeName);
let mark = 85;
console.log(typeof mark);
let age3 = 30;
age3 = 35;
console.log(age3);
let isStudent = true;
console.log(isStudent);
console.log(typeof isStudent);
const collegeName = "ABC University";
console.log(collegeName);
let price = 100;
let quantity = 3;
let totalPrice = price * quantity;
console.log(totalPrice);
let isActive = true;
console.log(isActive);
console.log(typeof isActive);
let price2 = 50;
console.log(price2);
console.log(typeof price2);